language: java
jdk: openjdk11
env:
  global:
  - secure: Ui6CesHum8MOmF5VFgHCjwtJVxMTwRLkuXqEaUPi9MfYiYnj/DnB1lH4p5gWinE8G2RHDhs3xmWEYq0/BQL2zzyLicpK+/I8GAuFiyzTLPoXHlT6+7ZjQyhKMAQE8gaUDIUT4b9w9xbbUQeSqm5yzj6vZXvbLjKw+HrUyxybL/0RkEAkfyU/9K3VaEXvZRjZBW+lYWHebNdG/8JdjRCz0OwfJG1Ni8jLn8OIRL+5scNKNFd1P+a7PQJRMDPJYcMGiv0xOVA+ryF2Tr/l2aKaD1ie5g4THclq58sGaqIC5W/eKQicWbbDUgrsdliJhdX2kiSWQJrqUyhL+B3wCbor6a73Dl4LxD7oFqN6dswWBlozl3y0k4nyKF2wtoTYhJp3UafHGg1Ywre93XFO4EkF8j4TKDQKGG4QMobxMsrYnXji2FXT4mWcM/hExloTwIuhZXzVXunFPEkuB90S6IGzLZW38iLOTIi0pRnABpB8pFTHJLdM2rOmbFtvfLmdzALaNmHCSCf0EOFBUmOmc3qJ84+YmVKS2dSO5PqwSN8QIYu82yxgHdFp4LQSsruavoAFCI5jBr4Rl5+IBbSef/zfXNMyjU8ENCs5GcTdeEIgzd/Xln7CMzsxB86hWtjUp3yk3IPtXLDevErSYHRmU0ezG5tsxTqBnzV6ugtQ/P5IZMQ=
  - secure: FIKte9FQ5109OcodMgkXasmE9j1dHRmw7SgRIK0elCFnpBlGbWBKAMp0x8Iz9tqHskJhP+ka20erAoHCRuXqVr63lMqM+EaWEzOuHaKCIcYogdAUiNseIsR0KfOHuT0zfUS4IKs0F+Mt71O+jBnolplsMLbn4+Ua5TQgU8xTIA9VLUeRC2jUnOmqLz/eSZZLa3qJRGqdUSZZqvdu4wsW3Hbub9yE8f5ak0zjVuWzyzcHRMVLMOxNFjRrPVoSTAhBAhHTZgHwdlVfMouAuzXt47+8G+u8TPjW/ycGWV92ZuxTCuzgsmCnLaTUFzYGt9m6yMuefLNTZn6li9r8/iOSZRqr9wIE1E51533xKgpgW/TEYSou4gQHQdZgzmzdiivE/ARJX+PIz4g0FBgsp+EGyqk91PlyVp4r9XQ1qGo0aPVp6fFtAj11wV9DCHluJZh9YSS+L07BGsMT10URfFPyMGjqBZ3JGVO8PoOlikBMGtJWSmqLAKEMUMByhFicoOF2lg4pf0STuKaJY9GDPoYTFnVWgfcebCNiDn9R7DFZEajCfUkZMKaR7LtbomvW4Dy9GBOneyS5Gh30LkofUBjzhASazD37CXlKoetfdtBRZbVxRn7kudx3qUpeGOna9WsRrbA4YFb7CA7tDFF/wBarr7wTHKEL5NUX4EQeN7xQJ5g=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
